--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _fluent_migrations; Type: TABLE; Schema: public; Owner: krzysztofkinal
--

CREATE TABLE public._fluent_migrations (
    id uuid NOT NULL,
    name text NOT NULL,
    batch bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);


ALTER TABLE public._fluent_migrations OWNER TO krzysztofkinal;

--
-- Name: challenges; Type: TABLE; Schema: public; Owner: krzysztofkinal
--

CREATE TABLE public.challenges (
    id bigint NOT NULL,
    challenge_type text NOT NULL,
    challenge_secret text NOT NULL
);


ALTER TABLE public.challenges OWNER TO krzysztofkinal;

--
-- Name: challenges_id_seq; Type: SEQUENCE; Schema: public; Owner: krzysztofkinal
--

ALTER TABLE public.challenges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: champions; Type: TABLE; Schema: public; Owner: krzysztofkinal
--

CREATE TABLE public.champions (
    id bigint NOT NULL,
    name text NOT NULL,
    gender text NOT NULL,
    "position" text[] NOT NULL,
    species text[] NOT NULL,
    resource text NOT NULL,
    range_type text NOT NULL,
    region text[] NOT NULL,
    release_year bigint NOT NULL
);


ALTER TABLE public.champions OWNER TO krzysztofkinal;

--
-- Name: champions_id_seq; Type: SEQUENCE; Schema: public; Owner: krzysztofkinal
--

ALTER TABLE public.champions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.champions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: statistics; Type: TABLE; Schema: public; Owner: krzysztofkinal
--

CREATE TABLE public.statistics (
    id bigint NOT NULL,
    challenge_type text NOT NULL,
    completions bigint NOT NULL
);


ALTER TABLE public.statistics OWNER TO krzysztofkinal;

--
-- Name: statistics_id_seq; Type: SEQUENCE; Schema: public; Owner: krzysztofkinal
--

ALTER TABLE public.statistics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.statistics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: _fluent_migrations; Type: TABLE DATA; Schema: public; Owner: krzysztofkinal
--

COPY public._fluent_migrations (id, name, batch, created_at, updated_at) FROM stdin;
5259bd84-2b1c-477b-9968-01d20329cf40	App.CreateChallenge	1	2022-09-01 20:33:17.39699+02	2022-09-01 20:33:17.39699+02
552af008-c166-45df-8cee-92dc7481a918	App.CreateStatistics	1	2022-09-01 20:33:17.406314+02	2022-09-01 20:33:17.406314+02
5b9c2a1e-76cb-4933-8777-e413fd79056e	App.CreateChampion	1	2022-09-01 20:33:17.414432+02	2022-09-01 20:33:17.414432+02
\.


--
-- Data for Name: challenges; Type: TABLE DATA; Schema: public; Owner: krzysztofkinal
--

COPY public.challenges (id, challenge_type, challenge_secret) FROM stdin;
2	ability	Aatrox
1	quote	Aatrox
3	splash	Aatrox
0	champion	Nunu & Willump
\.


--
-- Data for Name: champions; Type: TABLE DATA; Schema: public; Owner: krzysztofkinal
--

COPY public.champions (id, name, gender, "position", species, resource, range_type, region, release_year) FROM stdin;
266	Aatrox	male	{top}	{darkin,godWarrior}	manaless	melee	{runeterra,shurima}	2013
103	Ahri	female	{middle}	{vastayan}	mana	ranged	{ionia}	2011
84	Akali	female	{middle,top}	{human}	energy	melee	{ionia}	2010
166	Akshan	male	{middle,top}	{human}	mana	ranged	{shurima}	2021
12	Alistar	male	{support}	{minotaur}	mana	melee	{runeterra}	2009
32	Amumu	male	{jungle,support}	{undead,yordle}	mana	melee	{shurima}	2009
34	Anivia	female	{middle}	{god,spirit}	mana	ranged	{freljord}	2009
1	Annie	female	{middle}	{human,magicallyAltered}	mana	ranged	{runeterra}	2009
523	Aphelios	male	{bottom}	{human,spiritualist}	mana	ranged	{targon}	2019
22	Ashe	female	{bottom,support}	{human,iceborn}	mana	ranged	{freljord}	2009
136	Aurelion Sol	male	{middle}	{celestial,dragon}	mana	ranged	{runeterra,targon}	2016
268	Azir	male	{middle}	{godWarrior}	mana	ranged	{shurima}	2014
432	Bard	male	{support}	{celestial}	mana	ranged	{runeterra}	2015
53	Blitzcrank	other	{support}	{golem}	mana	melee	{zaun}	2009
63	Brand	male	{middle,support}	{human,magicallyAltered}	mana	ranged	{runeterra}	2011
201	Braum	male	{support}	{human,iceborn}	mana	melee	{freljord}	2014
200	Bel'Veth	female	{jungle}	{voidBeing}	manaless	melee	{void,shurima}	2022
51	Caitlyn	female	{bottom}	{human}	mana	ranged	{piltover}	2011
164	Camille	female	{top}	{cyborg,human}	mana	melee	{piltover}	2016
69	Cassiopeia	female	{middle,top}	{human,magicallyAltered}	mana	ranged	{noxus}	2010
31	Cho'Gath	male	{top}	{voidBeing}	mana	melee	{void}	2009
42	Corki	male	{middle}	{yordle}	mana	ranged	{bandleCity}	2009
122	Darius	male	{top}	{human}	mana	melee	{noxus}	2012
131	Diana	female	{jungle,middle}	{aspect,human}	mana	melee	{targon}	2012
36	Dr. Mundo	male	{jungle,top}	{chemicallyAltered,human}	health	melee	{zaun}	2009
119	Draven	male	{bottom}	{human}	mana	ranged	{noxus}	2012
245	Ekko	male	{jungle,middle}	{human}	mana	melee	{zaun}	2015
60	Elise	female	{jungle}	{human,magicallyAltered}	mana	both	{noxus,shadowIsles}	2012
28	Evelynn	female	{jungle}	{demon,spirit}	mana	melee	{runeterra}	2009
81	Ezreal	male	{bottom}	{human,magicborn}	mana	ranged	{piltover}	2010
9	Fiddlesticks	other	{jungle}	{demon,spirit}	mana	ranged	{runeterra}	2009
114	Fiora	female	{top}	{human}	mana	melee	{demacia}	2012
105	Fizz	male	{middle}	{yordle}	mana	melee	{bilgewater}	2011
3	Galio	male	{middle,support}	{golem}	mana	melee	{demacia}	2010
41	Gangplank	male	{middle,top}	{human}	mana	melee	{bilgewater}	2009
86	Garen	male	{top}	{human}	manaless	melee	{demacia}	2010
150	Gnar	male	{top}	{yordle}	rage	both	{freljord}	2014
79	Gragas	male	{jungle,top}	{human}	mana	melee	{freljord}	2010
104	Graves	male	{jungle}	{human}	mana	ranged	{bilgewater}	2011
887	Gwen	female	{top}	{human,magicallyAltered}	mana	melee	{camavor,shadowIsles}	2021
120	Hecarim	male	{jungle}	{undead}	mana	melee	{camavor,shadowIsles}	2012
74	Heimerdinger	male	{middle,support,top}	{yordle}	mana	ranged	{piltover}	2009
420	Illaoi	female	{top}	{human,spiritualist}	mana	melee	{bilgewater}	2015
39	Irelia	female	{middle,top}	{human,spiritualist}	mana	melee	{ionia}	2010
427	Ivern	male	{jungle}	{human,magicallyAltered}	mana	ranged	{freljord,ionia}	2016
40	Janna	female	{support}	{god,spirit}	mana	ranged	{shurima,zaun}	2009
59	Jarvan IV	male	{jungle}	{human}	mana	melee	{demacia}	2011
24	Jax	male	{top}	{unknown}	mana	melee	{icathia,runeterra,shurima}	2009
126	Jayce	male	{top}	{human}	mana	both	{piltover}	2012
202	Jhin	male	{bottom}	{human,spiritualist}	mana	ranged	{ionia}	2016
222	Jinx	female	{bottom}	{chemicallyAltered,human}	mana	ranged	{zaun}	2013
145	Kai'Sa	female	{bottom}	{human,voidBeing}	mana	ranged	{void}	2018
429	Kalista	female	{bottom}	{undead}	mana	ranged	{camavor,shadowIsles}	2014
43	Karma	female	{support}	{human,spiritualist}	mana	ranged	{ionia}	2011
30	Karthus	male	{top,jungle,middle,bottom}	{undead}	mana	ranged	{noxus,shadowIsles}	2009
38	Kassadin	male	{middle}	{human,voidBeing}	mana	melee	{void}	2009
55	Katarina	female	{middle}	{human}	manaless	melee	{noxus}	2009
10	Kayle	female	{top}	{aspect,human,magicallyAltered}	mana	both	{demacia,targon}	2009
141	Kayn	male	{jungle}	{darkin,human,magicallyAltered}	mana	melee	{ionia,noxus,rhaast,runeterra,shurima}	2017
85	Kennen	male	{top}	{yordle}	energy	ranged	{ionia}	2010
121	Kha'Zix	male	{jungle}	{voidBeing}	mana	melee	{void}	2012
203	Kindred	other	{jungle}	{god,spirit}	mana	ranged	{runeterra}	2015
240	Kled	male	{top}	{yordle}	courage	melee	{noxus}	2016
96	Kog'Maw	male	{bottom}	{voidBeing}	mana	ranged	{void}	2010
7	LeBlanc	female	{middle}	{human,magicallyAltered}	mana	ranged	{noxus}	2010
64	Lee Sin	male	{jungle}	{human,spiritualist}	energy	melee	{ionia}	2011
89	Leona	female	{support}	{aspect,human}	mana	melee	{targon}	2011
876	Lillia	female	{jungle,top}	{spirit}	mana	ranged	{ionia}	2020
127	Lissandra	female	{middle}	{human,iceborn}	mana	ranged	{freljord}	2013
236	Lucian	male	{bottom}	{human}	mana	ranged	{blessedIsles,demacia}	2013
117	Lulu	female	{support}	{yordle}	mana	ranged	{bandleCity}	2012
99	Lux	female	{middle,support}	{human,magicborn}	mana	ranged	{demacia}	2010
54	Malphite	male	{top}	{golem}	mana	melee	{ixtal,shurima}	2009
90	Malzahar	male	{middle}	{human,voidBeing}	mana	ranged	{void}	2010
57	Maokai	male	{support,top}	{spirit}	mana	melee	{blessedIsles,shadowIsles}	2011
11	Master Yi	male	{jungle}	{human,spiritualist}	mana	melee	{ionia}	2009
21	Miss Fortune	female	{bottom}	{human}	mana	ranged	{bilgewater}	2010
62	Wukong	male	{jungle,top}	{vastayan}	mana	melee	{ionia}	2011
82	Mordekaiser	male	{top}	{revenant}	shield	melee	{noxus}	2010
25	Morgana	female	{support}	{aspect,human,magicallyAltered}	mana	ranged	{demacia,targon}	2009
267	Nami	female	{support}	{vastayan}	mana	ranged	{runeterra}	2012
75	Nasus	male	{top}	{godWarrior}	mana	melee	{shurima}	2009
111	Nautilus	male	{support}	{revenant}	mana	melee	{bilgewater}	2012
518	Neeko	female	{middle,support}	{vastayan}	mana	ranged	{ixtal}	2018
76	Nidalee	female	{jungle}	{human,spiritualist,vastayan}	mana	both	{ixtal}	2009
895	Nilah	female	{bottom}	{human,magicallyAltered}	mana	melee	{kathkan,bilgewater}	2022
56	Nocturne	other	{jungle}	{demon,spirit}	mana	melee	{runeterra}	2011
20	Nunu & Willump	male	{jungle}	{human}	mana	melee	{freljord}	2009
2	Olaf	male	{jungle,top}	{human,iceborn}	mana	melee	{freljord}	2010
61	Orianna	female	{middle}	{golem}	mana	ranged	{piltover}	2011
516	Ornn	male	{top}	{god,spirit}	mana	melee	{freljord}	2017
80	Pantheon	male	{middle,support,top}	{human}	mana	melee	{targon}	2010
78	Poppy	female	{jungle,top}	{yordle}	mana	melee	{demacia}	2010
555	Pyke	male	{support}	{revenant}	mana	melee	{bilgewater}	2018
246	Qiyana	female	{jungle,middle}	{human,magicborn}	mana	melee	{ixtal}	2019
133	Quinn	female	{top}	{human}	mana	ranged	{demacia}	2013
497	Rakan	male	{support}	{vastayan}	mana	ranged	{ionia}	2017
33	Rammus	male	{jungle}	{godWarrior}	mana	melee	{shurima}	2009
421	Rek'Sai	female	{jungle}	{voidBeing}	rage	melee	{void}	2014
526	Rell	female	{support}	{human,magicallyAltered,magicborn}	mana	melee	{noxus}	2020
888	Renata Glasc	female	{support}	{chemicallyAltered,human}	mana	ranged	{zaun}	2022
58	Renekton	male	{top}	{godWarrior}	fury	melee	{shurima}	2011
107	Rengar	male	{jungle,top}	{vastayan}	ferocity	melee	{ixtal}	2012
92	Riven	female	{top}	{human}	manaless	melee	{ionia,noxus}	2011
68	Rumble	male	{middle,top}	{yordle}	mana	melee	{bandleCity}	2011
13	Ryze	male	{middle,top}	{human,magicallyAltered}	mana	ranged	{runeterra}	2009
360	Samira	female	{bottom}	{human}	mana	ranged	{noxus,shurima}	2020
113	Sejuani	female	{jungle,top}	{human,iceborn}	mana	melee	{freljord}	2012
235	Senna	female	{support}	{undead}	mana	ranged	{blessedIsles}	2019
147	Seraphine	female	{support}	{human,magicborn}	mana	ranged	{piltover,zaun}	2020
875	Sett	male	{top}	{human,vastayan}	grit	melee	{ionia}	2020
35	Shaco	male	{jungle,support}	{spirit}	mana	melee	{runeterra}	2009
98	Shen	male	{top}	{human,spiritualist}	energy	melee	{ionia}	2010
102	Shyvana	female	{jungle}	{dragon,magicallyAltered}	fury	melee	{demacia}	2011
27	Singed	male	{top}	{chemicallyAltered,human}	mana	melee	{piltover,zaun}	2009
14	Sion	male	{top}	{revenant}	mana	melee	{noxus}	2009
15	Sivir	female	{bottom}	{human}	mana	ranged	{shurima}	2009
72	Skarner	male	{jungle,top}	{brackern}	mana	melee	{shurima}	2011
37	Sona	female	{support}	{human,magicborn}	mana	ranged	{demacia}	2010
16	Soraka	female	{support}	{celestial}	mana	ranged	{ionia,targon}	2009
50	Swain	male	{middle,support}	{human,magicallyAltered}	mana	ranged	{noxus}	2010
517	Sylas	male	{middle}	{human,magicborn}	mana	melee	{demacia,freljord}	2019
134	Syndra	female	{middle}	{human,magicborn}	mana	ranged	{ionia}	2012
163	Taliyah	female	{jungle,middle}	{human,magicborn}	mana	ranged	{shurima}	2016
91	Talon	male	{jungle,middle}	{human}	mana	melee	{noxus}	2011
44	Taric	male	{support}	{aspect,human}	mana	melee	{demacia,targon}	2009
17	Teemo	male	{top}	{yordle}	mana	ranged	{bandleCity}	2009
412	Thresh	male	{support}	{undead}	mana	ranged	{blessedIsles,shadowIsles}	2013
18	Tristana	female	{bottom}	{yordle}	mana	ranged	{bandleCity}	2009
48	Trundle	male	{jungle,top}	{troll,iceborn}	mana	melee	{freljord}	2010
23	Tryndamere	male	{top}	{human,magicallyAltered}	fury	melee	{freljord}	2009
4	Twisted Fate	male	{middle}	{human,magicborn}	mana	ranged	{bilgewater}	2009
29	Twitch	male	{bottom}	{rat,chemicallyAltered}	mana	ranged	{zaun}	2009
77	Udyr	male	{jungle}	{human,spiritualist,vastayan}	mana	melee	{freljord,ionia}	2009
6	Urgot	male	{top}	{chemicallyAltered,cyborg,human}	mana	ranged	{noxus,zaun}	2010
110	Varus	male	{bottom}	{darkin,godWarrior,human}	mana	ranged	{ionia,runeterra,shurima}	2012
67	Vayne	female	{bottom,top}	{human}	mana	ranged	{demacia}	2011
45	Veigar	male	{middle}	{yordle}	mana	ranged	{bandleCity,runeterra}	2009
161	Vel'Koz	male	{middle,support}	{voidBeing}	mana	ranged	{void}	2014
711	Vex	female	{middle}	{yordle}	mana	ranged	{bandleCity,shadowIsles}	2021
254	Vi	female	{jungle}	{human}	mana	melee	{piltover,zaun}	2012
234	Viego	male	{jungle}	{undead}	manaless	melee	{camavor,shadowIsles}	2021
112	Viktor	male	{middle}	{cyborg,human}	mana	ranged	{zaun}	2011
8	Vladimir	male	{middle,top}	{human,magicallyAltered}	bloodthirst	ranged	{blessedIsles,camavor,noxus}	2010
106	Volibear	male	{top}	{god,spirit}	mana	melee	{freljord}	2011
19	Warwick	male	{jungle}	{chemicallyAltered,cyborg,human}	mana	melee	{zaun}	2009
498	Xayah	female	{bottom}	{vastayan}	mana	ranged	{ionia}	2017
101	Xerath	male	{middle,support}	{godWarrior}	mana	ranged	{shurima}	2011
5	Xin Zhao	male	{jungle}	{human}	mana	melee	{demacia,ionia,noxus}	2010
157	Yasuo	male	{middle}	{human,magicborn}	flow	melee	{ionia}	2013
777	Yone	male	{middle,top}	{human,magicallyAltered}	manaless	melee	{ionia}	2020
83	Yorick	male	{top}	{human,magicallyAltered}	mana	melee	{blessedIsles,shadowIsles}	2011
350	Yuumi	female	{support}	{cat,magicallyAltered}	mana	ranged	{bandleCity}	2019
154	Zac	male	{jungle}	{golem}	health	melee	{zaun}	2013
238	Zed	male	{jungle,middle}	{human,magicallyAltered}	energy	melee	{ionia}	2012
221	Zeri	female	{bottom}	{human,magicborn}	mana	ranged	{zaun}	2022
115	Ziggs	male	{bottom,middle}	{yordle}	mana	ranged	{piltover,zaun}	2012
26	Zilean	male	{middle,support}	{human,magicborn}	mana	ranged	{icathia,runeterra,shurima}	2009
142	Zoe	female	{middle}	{aspect,human}	mana	ranged	{targon}	2017
143	Zyra	female	{support}	{unknown}	mana	ranged	{ixtal}	2012
223	Tahm Kench	male	{top,support}	{demon,spirit}	mana	melee	{bilgewater,runeterra}	2015
\.


--
-- Data for Name: statistics; Type: TABLE DATA; Schema: public; Owner: krzysztofkinal
--

COPY public.statistics (id, challenge_type, completions) FROM stdin;
2	ability	0
3	splash	0
0	champion	0
1	quote	0
\.


--
-- Name: challenges_id_seq; Type: SEQUENCE SET; Schema: public; Owner: krzysztofkinal
--

SELECT pg_catalog.setval('public.challenges_id_seq', 1, false);


--
-- Name: champions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: krzysztofkinal
--

SELECT pg_catalog.setval('public.champions_id_seq', 1, false);


--
-- Name: statistics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: krzysztofkinal
--

SELECT pg_catalog.setval('public.statistics_id_seq', 1, false);


--
-- Name: _fluent_migrations _fluent_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: krzysztofkinal
--

ALTER TABLE ONLY public._fluent_migrations
    ADD CONSTRAINT _fluent_migrations_pkey PRIMARY KEY (id);


--
-- Name: challenges challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: krzysztofkinal
--

ALTER TABLE ONLY public.challenges
    ADD CONSTRAINT challenges_pkey PRIMARY KEY (id);


--
-- Name: champions champions_pkey; Type: CONSTRAINT; Schema: public; Owner: krzysztofkinal
--

ALTER TABLE ONLY public.champions
    ADD CONSTRAINT champions_pkey PRIMARY KEY (id);


--
-- Name: statistics statistics_pkey; Type: CONSTRAINT; Schema: public; Owner: krzysztofkinal
--

ALTER TABLE ONLY public.statistics
    ADD CONSTRAINT statistics_pkey PRIMARY KEY (id);


--
-- Name: _fluent_migrations uq:_fluent_migrations.name; Type: CONSTRAINT; Schema: public; Owner: krzysztofkinal
--

ALTER TABLE ONLY public._fluent_migrations
    ADD CONSTRAINT "uq:_fluent_migrations.name" UNIQUE (name);


--
-- PostgreSQL database dump complete
--

